### PR TITLE
Implement AsRawFd for SslStream to return -1

### PR DESCRIPTION
**Pull request by quangIO**
Per internal discussion with @inikulin, we should be able to return -1 as the raw fd of SslStream

### CODE REVIEW

**Comment by quangIO** [comment]
> Why is this useful?

The use case is: we have a custom Socket trait. Some sockets are transferable (as in, can be sent to other processes), and some are not. SslStream is a non transferable socket as it manipulates bytestream.

**Comment by jyn514** [comment]
> We are implementing other trait for that, but doing this directly using AsRawFd doesn't hurt.

I don't quite understand; if you're already implementing the other trait, why do you also need AsRawFd? I worry this will be very surprising for people who expect AsRawFd to always return a valid file descriptor.

**Comment by Noah-Kennedy** [comment]
I'm in agreement with @jyn514. `AsRawFd` shouldn't be used for situations like this.

**Comment by nox** [comment]
Closing this as it seems we don't want to do that.

**Pull request closed without merging**
