### PR TITLE
Fix clippy errors.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotr@aviatrix.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
cc @inikulin

**Comment by inikulin** [comment]
@PiotrSikora thanks for the PR! Seems like more fixes are needed for the recent clippy update (see CI failures)

**Comment by PiotrSikora** [comment]
> @PiotrSikora thanks for the PR! Seems like more fixes are needed for the recent clippy update (see CI failures)

I don't like that `clippy` is forcing this style, but I've updated the PR accordingly. PTAL.

**Comment by PiotrSikora** [comment]
This is now failing due to `clang-7` package being no longer available on the CI. This will be fixed in #97, and `clippy` tests are passing in this PR, so it should be good to merge.

**Comment by PiotrSikora** [comment]
@inikulin could you take another pass? As mentioned in the previous comment, this PR fixes `clippy` test, and the `FIPS integration` is fixed in #97, so merging both will fix the CI.

**Comment by nox** [comment]
Superseded by #116.

**Pull request closed without merging**
